language: node_js
node_js:
  - "4"
  - "6"
os:
  - linux
  - osx
osx_image: xcode8
install:
  - npm install
  - npm run lint
script:
  - npm run build-and-test
# cache:
#   directories:
#     - node_modules
